// Minimal stubs for flang Fortran runtime functions
// Signatures derived from LLVM IR declarations generated by flang.
// In wasm64 (MEMORY64) mode: ptr=i64, size_t=i64, bool=i1(zeroext)

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <math.h>
#include <stdbool.h>

// =====================================================
// I/O Runtime
// =====================================================
static int _io_active = 0;

// ptr @BeginExternalListOutput(i32 unit, ptr source_file, i32 source_line)
void *_FortranAioBeginExternalListOutput(int unit, const char *sf, int sl) {
  return &_io_active;
}
// ptr @BeginExternalListInput(i32, ptr, i32)
void *_FortranAioBeginExternalListInput(int unit, const char *sf, int sl) {
  return &_io_active;
}
// ptr @BeginExternalFormattedOutput(ptr fmt, i64 fmt_len, ptr ?, i32 unit, ptr sf, i32 sl)
void *_FortranAioBeginExternalFormattedOutput(const char *fmt, size_t fmt_len,
    void *scratch, int unit, const char *sf, int sl) {
  return &_io_active;
}
// ptr @BeginUnformattedOutput(i32, ptr, i32)
void *_FortranAioBeginUnformattedOutput(int unit, const char *sf, int sl) {
  return &_io_active;
}
// ptr @BeginUnformattedInput(i32, ptr, i32)
void *_FortranAioBeginUnformattedInput(int unit, const char *sf, int sl) {
  return &_io_active;
}
// ptr @BeginInternalFormattedOutput(ptr buf, i64 buf_len, ptr fmt, i64 fmt_len, ptr scratch, ptr ?, i64 ?, ptr sf, i32 sl)
void *_FortranAioBeginInternalFormattedOutput(char *buf, size_t buf_len,
    const char *fmt, size_t fmt_len, void *scratch, void *p1, size_t s1,
    const char *sf, int sl) {
  return &_io_active;
}
// ptr @BeginOpenUnit(i32, ptr, i32)
void *_FortranAioBeginOpenUnit(int unit, const char *sf, int sl) {
  return &_io_active;
}
// ptr @BeginClose(i32, ptr, i32)
void *_FortranAioBeginClose(int unit, const char *sf, int sl) {
  return &_io_active;
}
// ptr @BeginInquireUnit(i32, ptr, i32)
void *_FortranAioBeginInquireUnit(int unit, const char *sf, int sl) {
  return &_io_active;
}
// ptr @BeginInquireFile(ptr, i64, ptr, i32)
void *_FortranAioBeginInquireFile(const char *path, size_t path_len,
    const char *sf, int sl) {
  return &_io_active;
}

// bool @OutputAscii(ptr cookie, ptr str, i64 len)
bool _FortranAioOutputAscii(void *c, const char *str, size_t len) {
  if (str && len > 0) fprintf(stderr, "%.*s", (int)len, str);
  return true;
}
// bool @OutputInteger32(ptr, i32)
bool _FortranAioOutputInteger32(void *c, int32_t val) {
  fprintf(stderr, " %d", val); return true;
}
// bool @OutputInteger64(ptr, i64)
bool _FortranAioOutputInteger64(void *c, int64_t val) {
  fprintf(stderr, " %lld", (long long)val); return true;
}
// bool @OutputReal32(ptr, float)
bool _FortranAioOutputReal32(void *c, float val) {
  fprintf(stderr, " %g", val); return true;
}
// bool @OutputReal64(ptr, double)
bool _FortranAioOutputReal64(void *c, double val) {
  fprintf(stderr, " %g", val); return true;
}
// bool @OutputLogical(ptr, i1 zeroext)
bool _FortranAioOutputLogical(void *c, bool val) {
  fprintf(stderr, " %s", val ? "T" : "F"); return true;
}
// bool @OutputDescriptor(ptr, ptr)
bool _FortranAioOutputDescriptor(void *c, void *desc) {
  fprintf(stderr, " <array>"); return true;
}
// bool @InputDescriptor(ptr, ptr)
bool _FortranAioInputDescriptor(void *c, void *desc) { return true; }
// bool @InputInteger(ptr, ptr, i32)
bool _FortranAioInputInteger(void *c, void *dest, int kind) {
  if (dest) memset(dest, 0, kind); return true;
}
// bool @InputReal64(ptr, ptr)
bool _FortranAioInputReal64(void *c, double *dest) {
  if (dest) *dest = 0.0; return true;
}

// void @EnableHandlers(ptr, i1, i1, i1, i1, i1)
void _FortranAioEnableHandlers(void *c, bool a, bool b, bool d, bool e, bool f) {}

// bool @SetAccess(ptr, ptr, i64)
bool _FortranAioSetAccess(void *c, const char *s, size_t len) { return true; }
// bool @SetAdvance(ptr, ptr, i64)
bool _FortranAioSetAdvance(void *c, const char *s, size_t len) { return true; }
// bool @SetFile(ptr, ptr, i64)
bool _FortranAioSetFile(void *c, const char *s, size_t len) { return true; }
// bool @SetForm(ptr, ptr, i64)
bool _FortranAioSetForm(void *c, const char *s, size_t len) { return true; }
// bool @SetStatus(ptr, ptr, i64)
bool _FortranAioSetStatus(void *c, const char *s, size_t len) { return true; }
// bool @InquireLogical(ptr, i64, ptr)
bool _FortranAioInquireLogical(void *c, int64_t key, bool *result) {
  if (result) *result = false; return true;
}

// i32 @EndIoStatement(ptr)
int _FortranAioEndIoStatement(void *c) {
  fprintf(stderr, "\n"); return 0;
}

// =====================================================
// Memory: Allocatable
// =====================================================
// void @AllocatableSetBounds(ptr, i32, i64, i64)
void _FortranAAllocatableSetBounds(void *desc, int dim, int64_t lb, int64_t ub) {}
// i32 @AllocatableAllocate(ptr, ptr, i1 zeroext, ptr, ptr, i32, ptr)
int _FortranAAllocatableAllocate(void *desc, void *errMsg, bool hasStat,
    void *stat, void *p1, int sl_int, void *sf) { return 0; }
// i32 @AllocatableDeallocate(ptr, i1 zeroext, ptr, ptr, i32)
int _FortranAAllocatableDeallocate(void *desc, bool hasStat, void *stat,
    void *errMsg, int sl) { return 0; }

// =====================================================
// Memory: Pointer
// =====================================================
// void @PointerSetBounds(ptr, i32, i64, i64)
void _FortranAPointerSetBounds(void *desc, int dim, int64_t lb, int64_t ub) {}
// i32 @PointerAllocate(ptr, i1 zeroext, ptr, ptr, i32, ptr)
int _FortranAPointerAllocate(void *desc, bool hasStat, void *stat,
    void *errMsg, int sl, void *sf) { return 0; }
// i32 @PointerDeallocate(ptr, i1 zeroext, ptr, ptr, i32)
int _FortranAPointerDeallocate(void *desc, bool hasStat, void *stat,
    void *errMsg, int sl) { return 0; }
// bool @PointerIsAssociatedWith(ptr, ptr)
bool _FortranAPointerIsAssociatedWith(void *ptr, void *target) { return false; }

// =====================================================
// Derived types / Assignment
// =====================================================
// void @Initialize(ptr, ptr, i32)
void _FortranAInitialize(void *desc, void *typeInfo, int sl) {}
// void @Assign(ptr, ptr, ptr, i32)
void _FortranAAssign(void *to, void *from, const char *sf, int sl) {}
void _FortranAAssignTemporary(void *to, void *from, const char *sf, int sl) {}
// void @AssignExplicitLengthCharacter(ptr, ptr, ptr, i32)
void _FortranAAssignExplicitLengthCharacter(void *to, void *from, const char *sf, int sl) {}
// void @Transfer(ptr, ptr, ptr, ptr, i32)
void _FortranATransfer(void *result, void *source, void *mold, const char *sf, int sl) {}

// =====================================================
// Character
// =====================================================
// i32 @CharacterCompareScalar1(ptr, ptr, i64, i64)
int _FortranACharacterCompareScalar1(const char *a, const char *b,
    size_t a_len, size_t b_len) {
  size_t min_len = a_len < b_len ? a_len : b_len;
  for (size_t i = 0; i < min_len; i++) {
    if (a[i] != b[i]) return a[i] < b[i] ? -1 : 1;
  }
  if (a_len < b_len) {
    for (size_t i = a_len; i < b_len; i++)
      if (' ' != b[i]) return ' ' < b[i] ? -1 : 1;
  } else if (b_len < a_len) {
    for (size_t i = b_len; i < a_len; i++)
      if (a[i] != ' ') return a[i] < ' ' ? -1 : 1;
  }
  return 0;
}
// void @Trim(ptr result, ptr string, ptr sf, i32 sl)
void _FortranATrim(void *result, void *string, const char *sf, int sl) {
  if (result && string) memcpy(result, string, 64);
}
// void @Adjustl(ptr result, ptr string, ptr sf, i32 sl)
void _FortranAAdjustl(void *result, void *string, const char *sf, int sl) {
  if (result && string) memcpy(result, string, 64);
}

// =====================================================
// Numeric intrinsics
// =====================================================
// i32 @Exponent8_4(double)
int _FortranAExponent8_4(double x) {
  if (x == 0.0) return 0;
  int exp;
  frexp(x, &exp);
  return exp;
}
// double @Fraction8(double)
double _FortranAFraction8(double x) {
  if (x == 0.0) return 0.0;
  int exp;
  return frexp(x, &exp) * 2.0;
}

// =====================================================
// Array reduction intrinsics
// All take: (ptr array, ptr source_file, i32 kind, i32 source_line, ptr mask)
// =====================================================
// i32 @MaxvalInteger4(ptr, ptr, i32, i32, ptr)
int32_t _FortranAMaxvalInteger4(void *array, const char *sf, int kind, int sl, void *mask) { return 0; }
// i32 @MinvalInteger4(ptr, ptr, i32, i32, ptr)
int32_t _FortranAMinvalInteger4(void *array, const char *sf, int kind, int sl, void *mask) { return 0; }
// i32 @SumInteger4(ptr, ptr, i32, i32, ptr)
int32_t _FortranASumInteger4(void *array, const char *sf, int kind, int sl, void *mask) { return 0; }
// i64 @SumInteger8(ptr, ptr, i32, i32, ptr)
int64_t _FortranASumInteger8(void *array, const char *sf, int kind, int sl, void *mask) { return 0; }
// double @MaxvalReal8(ptr, ptr, i32, i32, ptr)
double _FortranAMaxvalReal8(void *array, const char *sf, int kind, int sl, void *mask) { return 0.0; }
// double @MinvalReal8(ptr, ptr, i32, i32, ptr)
double _FortranAMinvalReal8(void *array, const char *sf, int kind, int sl, void *mask) { return 0.0; }
// double @SumReal8(ptr, ptr, i32, i32, ptr)
double _FortranASumReal8(void *array, const char *sf, int kind, int sl, void *mask) { return 0.0; }
// i64 @Count(ptr, ptr, i32, i32)
int64_t _FortranACount(void *array, const char *sf, int kind, int sl) { return 0; }

// void @MaxlocDim(ptr result, ptr array, i32 dim, i32 kind, ptr sf, i32 sl, ptr mask, i1 back)
void _FortranAMaxlocDim(void *result, void *array, int dim, int kind,
    const char *sf, int sl, void *mask, bool back) {}

// =====================================================
// Random
// =====================================================
// void @RandomNumber(ptr, ptr, i32)
void _FortranARandomNumber(void *harvest, const char *sf, int sl) {}

// =====================================================
// Date/Time
// =====================================================
// void @DateAndTime(ptr, i64, ptr, i64, ptr, i64, ptr, i32, ptr)
void _FortranADateAndTime(void *date, size_t date_len, void *time, size_t time_len,
    void *zone, size_t zone_len, void *values, int sl, void *sf) {}

// =====================================================
// Stop / Abort
// =====================================================
// void @StopStatement(i32, i1 zeroext, i1 zeroext)
void _FortranAStopStatement(int code, bool isError, bool quiet) {
  if (!quiet) fprintf(stderr, "Fortran STOP (code %d)\n", code);
}
// void @StopStatementText(ptr, i64, i1 zeroext, i1 zeroext)
void _FortranAStopStatementText(const char *text, size_t len, bool isError, bool quiet) {
  if (!quiet && text && len > 0) fprintf(stderr, "Fortran STOP: %.*s\n", (int)len, text);
}
void _FortranAProgramEndStatement(void) {}
void _FortranAAbort(void) { abort(); }

// =====================================================
// System
// =====================================================
void _FortranASystemClockCount(int kind, void *count, void *rate, void *max) {
  if (count) memset(count, 0, kind);
}
void _FortranACpuTime(int kind, void *time) {
  if (time) memset(time, 0, kind);
}
